name:                tesi-benchmark
version:             0.1.0.0
github:              "flavio-a/tesi-benchmark"
license:             MIT
author:              "Flavio"
maintainer:          "flavio.a.618@gmail.com"
copyright:           "2019 Flavio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flavio-a/tesi-benchmark#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - src
  dependencies:
    - parallel
    - monad-par
    - repa
    - random
    - deepseq

executables:
  tesi-benchmark:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tesi-benchmark
      - criterion
      - deepseq
      - repa

tests:
  tesi-benchmark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tesi-benchmark
      - hspec
      - hspec-discover
